spring.application.name=officeManagementApp

#mysql connection
spring.datasource.url=jdbc:mysql://localhost/vnc
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# api suffix
server.servlet.contextPath=/api

#env variables
spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationDays= 7